# Generated by Django 5.2.8 on 2025-12-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created_at']},
        ),
    ]
